//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:src/main/webapp/app/entities/entity.service.ts.e.vm
//
import { Injectable } from '@angular/core';
import { HttpModule, Http, Response, Headers, RequestOptions } from '@angular/http';
import { LazyLoadEvent } from 'primeng/primeng';
import { Observable } from 'rxjs/Observable';
import { MessageService } from '../../service/message.service';
import { PageResponse, PageRequestByExample } from '../../support/paging';
import { ComponentConfig } from './componentConfig';

@Injectable()
export class ComponentConfigService {

    private options = new RequestOptions({ headers: new Headers({ 'Content-Type': 'application/json' }) });

    constructor(private http: Http, private messageService : MessageService) {}

    /**
     * Get a ComponentConfig by id.
     */
    getComponentConfig(id : any) : Observable<ComponentConfig> {
        return this.http.get('http://localhost:8080/api/componentConfigs/' + id)
            .map(response => <ComponentConfig> response.json())
            .catch(this.handleError);
    }

    /**
     * Update the passed componentConfig.
     */
    update(componentConfig : ComponentConfig) : Observable<ComponentConfig> {
        let body = JSON.stringify(componentConfig);

        return this.http.put('http://localhost:8080/api/componentConfigs/', body, this.options)
            .map(response => <ComponentConfig> response.json())
            .catch(this.handleError);
    }

    /**
     * Load a page (for paginated datatable) of ComponentConfig using the passed
     * componentConfig as an example for the search by example facility.
     */
    getPage(componentConfig : ComponentConfig, event : LazyLoadEvent) : Observable<PageResponse<ComponentConfig>> {
        let req = new PageRequestByExample(componentConfig, event);
        let body = JSON.stringify(req);

        return this.http.post('http://localhost:8080/api/componentConfigs/page', body, this.options)
            .map(response => {
                let pr = <PageResponse<ComponentConfig>> response.json();
                return new PageResponse<ComponentConfig>(pr.totalPages, pr.totalElements, pr.content);
            })
            .catch(this.handleError);
    }

    /**
     * Performs a search by example on 1 attribute (defined on server side) and returns at most 10 results.
     * Used by ComponentConfigCompleteComponent.
     */
    complete(query : string) : Observable<ComponentConfig[]> {
        let body = JSON.stringify({'query': query, 'maxResults': 10});
        return this.http.post('http://localhost:8080/api/componentConfigs/complete', body, this.options)
            .map(response => <ComponentConfig[]> response.json())
            .catch(this.handleError);
    }

    /**
     * Delete an ComponentConfig by id.
     */
    delete(id : any) {
        return this.http.delete('http://localhost:8080/api/componentConfigs/' + id).catch(this.handleError);
    }

    // sample method from angular doc
    private handleError (error: any) {
        // TODO: seems we cannot use messageService from here...
        let errMsg = (error.message) ? error.message :
        error.status ? `Status: ${error.status} - Text: ${error.statusText}` : 'Server error';
        console.error(errMsg); // log to console instead
        return Observable.throw(errMsg);
    }
}
