//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:src/main/webapp/app/entities/entity-list.component.ts.e.vm
//
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { Router } from '@angular/router';
import { LazyLoadEvent } from 'primeng/primeng';
import { PageResponse } from "../../support/paging";
import { MessageService } from '../../service/message.service';
import { ServerType } from './serverType';
import { ServerTypeDetailComponent } from './serverType-detail.component';
import { ServerTypeService } from './serverType.service';


@Component({
    moduleId: module.id,
	templateUrl: 'serverType-list.component.html',
	selector: 'serverType-list',
})
export class ServerTypeListComponent {

    @Input() header = "All ServerTypes...";

    // when sub is true, it means this list is a one-to-many list.
    // It belongs to a parent entity, as a result the addNew operation
    // must prefill the parent entity. The prefill is not done here, instead we
    // emit an event.
    @Input() sub : boolean;
    @Output() onAddNewClicked = new EventEmitter();

    serverTypeToDelete : ServerType;
    displayDeleteDialog : boolean;

    private example : ServerType = null; // used to query by example...

    // list is paginated
    currentPage : PageResponse<ServerType> = new PageResponse<ServerType>(0,0,[]);


    constructor(private router:Router, private serverTypeService : ServerTypeService, private messageService : MessageService) { }

    loadPage(event : LazyLoadEvent) {
        this.serverTypeService.getPage(this.example, event).
            subscribe(
                pageResponse => this.currentPage = pageResponse,
                error => this.messageService.error('Could not get the results', error)
            );
    }

    onRowSelect(event : any) {
        this.router.navigate(['/serverType', event.data.id]);
    }

    addNew() {
        if (this.sub) {
            this.onAddNewClicked.emit("addNew");
        } else {
            this.router.navigate(['/serverType', 'new']);
        }
    }

    showDeleteDialog(rowData : any) {
        this.serverTypeToDelete = <ServerType> rowData;
        this.displayDeleteDialog = true;
    }

    // delete + remove from current page
    delete() {
        this.serverTypeService.delete(this.serverTypeToDelete.id).
            subscribe(
                response => {
                    this.currentPage.remove(this.serverTypeToDelete);
                    this.displayDeleteDialog = false;
                    this.serverTypeToDelete = null;
                    this.messageService.info('Deleted OK', 'PrimeNG Rocks ;-)');
                },
                error => this.messageService.error('Could not delete!', error)
            );
    }
}