//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:src/main/webapp/app/entities/entity-detail.component.ts.e.vm
//
import {Component, OnInit, OnDestroy, Input, Output, EventEmitter} from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { SelectItem } from 'primeng/primeng';
import { MessageService} from '../../service/message.service';
import {ReleaseDataType} from './releaseDataType';
import {ReleaseDataTypeService} from './releaseDataType.service';

@Component({
    moduleId: module.id,
	templateUrl: 'releaseDataType-detail.component.html',
	selector: 'releaseDataType-detail',
})
export class ReleaseDataTypeDetailComponent implements OnInit, OnDestroy {
    releaseDataType : ReleaseDataType;

    private params_subscription: any;


    @Input() sub : boolean = false;
    @Output() onSaveClicked = new EventEmitter<ReleaseDataType>();
    @Output() onCancelClicked = new EventEmitter();

    constructor(private route: ActivatedRoute, private router: Router, private messageService: MessageService, private releaseDataTypeService: ReleaseDataTypeService) {
    }

    ngOnInit() {
        if (this.sub) {
            return;
        }

        this.params_subscription = this.route.params.subscribe(params => {
            let id = params['id'];
            console.log('ngOnInit for releaseDataType-detail ' + id);

            if (id === 'new') {
                this.releaseDataType = new ReleaseDataType();
            } else {
                this.releaseDataTypeService.getReleaseDataType(id)
                    .subscribe(
                        releaseDataType => this.releaseDataType = releaseDataType,
                        error =>  this.messageService.error('ngOnInit error', error)
                    );
            }
        });
    }

    ngOnDestroy() {
        if (!this.sub) {
            this.params_subscription.unsubscribe();
        }
    }

    onSave() {
        this.releaseDataTypeService.update(this.releaseDataType).
            subscribe(
                releaseDataType => {
                    this.releaseDataType = releaseDataType;
                    if (this.sub) {
                        this.onSaveClicked.emit(this.releaseDataType);
                        this.messageService.info('Saved OK and msg emitted', 'PrimeNG Rocks ;-)')
                    } else {
                        this.messageService.info('Saved OK', 'PrimeNG Rocks ;-)')
                    }
                },
                error =>  this.messageService.error('Could not save', error)
            );
    }

    onCancel() {
        if (this.sub) {
            this.onCancelClicked.emit("cancel");
            this.messageService.info('Cancel clicked and msg emitted', 'PrimeNG Rocks ;-)')
        }
    }

}
