//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:src/main/webapp/app/entities/entity-list.component.ts.e.vm
//
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { Router } from '@angular/router';
import { LazyLoadEvent } from 'primeng/primeng';
import { PageResponse } from "../../support/paging";
import { MessageService } from '../../service/message.service';
import { SolutionComponent } from './solutionComponent';
import { SolutionComponentDetailComponent } from './solutionComponent-detail.component';
import { SolutionComponentService } from './solutionComponent.service';

import { PackageInfo } from '../packageInfo/packageInfo';
import { PackageInfoLineComponent } from '../packageInfo/packageInfo-line.component';

@Component({
    moduleId: module.id,
	templateUrl: 'solutionComponent-list.component.html',
	selector: 'solutionComponent-list',
})
export class SolutionComponentListComponent {

    @Input() header = "All SolutionComponents...";

    // when sub is true, it means this list is a one-to-many list.
    // It belongs to a parent entity, as a result the addNew operation
    // must prefill the parent entity. The prefill is not done here, instead we
    // emit an event.
    @Input() sub : boolean;
    @Output() onAddNewClicked = new EventEmitter();

    solutionComponentToDelete : SolutionComponent;
    displayDeleteDialog : boolean;

    private example : SolutionComponent = null; // used to query by example...

    // list is paginated
    currentPage : PageResponse<SolutionComponent> = new PageResponse<SolutionComponent>(0,0,[]);

    // Many to one: input param is used to filter the list when displayed
    // as a one-to-many list by the other side.
    private _packageInfo : PackageInfo;

    constructor(private router:Router, private solutionComponentService : SolutionComponentService, private messageService : MessageService) { }

    loadPage(event : LazyLoadEvent) {
        this.solutionComponentService.getPage(this.example, event).
            subscribe(
                pageResponse => this.currentPage = pageResponse,
                error => this.messageService.error('Could not get the results', error)
            );
    }

    // Many to one: input param is used to filter the list when displayed
    // as a one-to-many list by the other side.
    @Input()
    set packageInfo(packageInfo : PackageInfo) {
        if (packageInfo == null) {
            return;
        }
        this._packageInfo = packageInfo;

        this.example = new SolutionComponent();
        this.example.packageInfo = new PackageInfo();
        this.example.packageInfo.id = this._packageInfo.id;
    }


    onRowSelect(event : any) {
        this.router.navigate(['/solutionComponent', event.data.id]);
    }

    addNew() {
        if (this.sub) {
            this.onAddNewClicked.emit("addNew");
        } else {
            this.router.navigate(['/solutionComponent', 'new']);
        }
    }

    showDeleteDialog(rowData : any) {
        this.solutionComponentToDelete = <SolutionComponent> rowData;
        this.displayDeleteDialog = true;
    }

    // delete + remove from current page
    delete() {
        this.solutionComponentService.delete(this.solutionComponentToDelete.id).
            subscribe(
                response => {
                    this.currentPage.remove(this.solutionComponentToDelete);
                    this.displayDeleteDialog = false;
                    this.solutionComponentToDelete = null;
                    this.messageService.info('Deleted OK', 'PrimeNG Rocks ;-)');
                },
                error => this.messageService.error('Could not delete!', error)
            );
    }
}