//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:src/main/webapp/app/entities/entity-line.component.ts.e.vm
//
import {Component, Input} from '@angular/core';
import {PackageType} from './packageType';

@Component({
	template: `
        {{ packageType.name }} 	`,
	selector: 'packageType-line',
})
export class PackageTypeLineComponent {
    @Input() packageType : PackageType;
}
