//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:src/main/webapp/app/entities/entity-list.component.ts.e.vm
//
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { Router } from '@angular/router';
import { LazyLoadEvent } from 'primeng/primeng';
import { PageResponse } from "../../support/paging";
import { MessageService } from '../../service/message.service';
import { PackageType } from './packageType';
import { PackageTypeDetailComponent } from './packageType-detail.component';
import { PackageTypeService } from './packageType.service';


@Component({
    moduleId: module.id,
	templateUrl: 'packageType-list.component.html',
	selector: 'packageType-list',
})
export class PackageTypeListComponent {

    @Input() header = "All PackageTypes...";

    // when sub is true, it means this list is a one-to-many list.
    // It belongs to a parent entity, as a result the addNew operation
    // must prefill the parent entity. The prefill is not done here, instead we
    // emit an event.
    @Input() sub : boolean;
    @Output() onAddNewClicked = new EventEmitter();

    packageTypeToDelete : PackageType;
    displayDeleteDialog : boolean;

    private example : PackageType = null; // used to query by example...

    // list is paginated
    currentPage : PageResponse<PackageType> = new PageResponse<PackageType>(0,0,[]);


    constructor(private router:Router, private packageTypeService : PackageTypeService, private messageService : MessageService) { }

    loadPage(event : LazyLoadEvent) {
        this.packageTypeService.getPage(this.example, event).
            subscribe(
                pageResponse => this.currentPage = pageResponse,
                error => this.messageService.error('Could not get the results', error)
            );
    }

    onRowSelect(event : any) {
        this.router.navigate(['/packageType', event.data.id]);
    }

    addNew() {
        if (this.sub) {
            this.onAddNewClicked.emit("addNew");
        } else {
            this.router.navigate(['/packageType', 'new']);
        }
    }

    showDeleteDialog(rowData : any) {
        this.packageTypeToDelete = <PackageType> rowData;
        this.displayDeleteDialog = true;
    }

    // delete + remove from current page
    delete() {
        this.packageTypeService.delete(this.packageTypeToDelete.id).
            subscribe(
                response => {
                    this.currentPage.remove(this.packageTypeToDelete);
                    this.displayDeleteDialog = false;
                    this.packageTypeToDelete = null;
                    this.messageService.info('Deleted OK', 'PrimeNG Rocks ;-)');
                },
                error => this.messageService.error('Could not delete!', error)
            );
    }
}