//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:src/main/webapp/app/app.routes.ts.p.vm
//
import { ModuleWithProviders }  from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

import { HomeComponent } from './home.component';

import { ComponentConfigListComponent } from './entities/componentConfig/componentConfig-list.component';
import { ComponentConfigDetailComponent } from './entities/componentConfig/componentConfig-detail.component';

import { EnvironmentListComponent } from './entities/environment/environment-list.component';
import { EnvironmentDetailComponent } from './entities/environment/environment-detail.component';

import { EnvironmentConfigListComponent } from './entities/environmentConfig/environmentConfig-list.component';
import { EnvironmentConfigDetailComponent } from './entities/environmentConfig/environmentConfig-detail.component';

import { GlobalconfigListComponent } from './entities/globalconfig/globalconfig-list.component';
import { GlobalconfigDetailComponent } from './entities/globalconfig/globalconfig-detail.component';

import { PackageInfoListComponent } from './entities/packageInfo/packageInfo-list.component';
import { PackageInfoDetailComponent } from './entities/packageInfo/packageInfo-detail.component';

import { PackageTypeListComponent } from './entities/packageType/packageType-list.component';
import { PackageTypeDetailComponent } from './entities/packageType/packageType-detail.component';

import { ReleaseListComponent } from './entities/release/release-list.component';
import { ReleaseDetailComponent } from './entities/release/release-detail.component';

import { ReleaseDataListComponent } from './entities/releaseData/releaseData-list.component';
import { ReleaseDataDetailComponent } from './entities/releaseData/releaseData-detail.component';

import { ReleaseDataTypeListComponent } from './entities/releaseDataType/releaseDataType-list.component';
import { ReleaseDataTypeDetailComponent } from './entities/releaseDataType/releaseDataType-detail.component';

import { ServerListComponent } from './entities/server/server-list.component';
import { ServerDetailComponent } from './entities/server/server-detail.component';

import { ServerConfigListComponent } from './entities/serverConfig/serverConfig-list.component';
import { ServerConfigDetailComponent } from './entities/serverConfig/serverConfig-detail.component';

import { ServerTypeListComponent } from './entities/serverType/serverType-list.component';
import { ServerTypeDetailComponent } from './entities/serverType/serverType-detail.component';

import { SolutionComponentListComponent } from './entities/solutionComponent/solutionComponent-list.component';
import { SolutionComponentDetailComponent } from './entities/solutionComponent/solutionComponent-detail.component';

export const routes: Routes = [
    { path : '',  component: HomeComponent }
    ,
    {path: 'componentConfig-list', component: ComponentConfigListComponent },
    {path: 'componentConfig/:id', component: ComponentConfigDetailComponent }
    ,
    {path: 'environment-list', component: EnvironmentListComponent },
    {path: 'environment/:id', component: EnvironmentDetailComponent }
    ,
    {path: 'environmentConfig-list', component: EnvironmentConfigListComponent },
    {path: 'environmentConfig/:id', component: EnvironmentConfigDetailComponent }
    ,
    {path: 'globalconfig-list', component: GlobalconfigListComponent },
    {path: 'globalconfig/:id', component: GlobalconfigDetailComponent }
    ,
    {path: 'packageInfo-list', component: PackageInfoListComponent },
    {path: 'packageInfo/:id', component: PackageInfoDetailComponent }
    ,
    {path: 'packageType-list', component: PackageTypeListComponent },
    {path: 'packageType/:id', component: PackageTypeDetailComponent }
    ,
    {path: 'release-list', component: ReleaseListComponent },
    {path: 'release/:id', component: ReleaseDetailComponent }
    ,
    {path: 'releaseData-list', component: ReleaseDataListComponent },
    {path: 'releaseData/:id', component: ReleaseDataDetailComponent }
    ,
    {path: 'releaseDataType-list', component: ReleaseDataTypeListComponent },
    {path: 'releaseDataType/:id', component: ReleaseDataTypeDetailComponent }
    ,
    {path: 'server-list', component: ServerListComponent },
    {path: 'server/:id', component: ServerDetailComponent }
    ,
    {path: 'serverConfig-list', component: ServerConfigListComponent },
    {path: 'serverConfig/:id', component: ServerConfigDetailComponent }
    ,
    {path: 'serverType-list', component: ServerTypeListComponent },
    {path: 'serverType/:id', component: ServerTypeDetailComponent }
    ,
    {path: 'solutionComponent-list', component: SolutionComponentListComponent },
    {path: 'solutionComponent/:id', component: SolutionComponentDetailComponent }
];

export const routing: ModuleWithProviders = RouterModule.forRoot(routes);
