//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:src/main/webapp/app/entities/entity-list.component.ts.e.vm
//
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { Router } from '@angular/router';
import { LazyLoadEvent, FilterMetadata } from 'primeng/primeng';
import { PageResponse } from "../../support/paging";
import { MessageService } from '../../service/message.service';
import { Server } from './server';
import { ServerDetailComponent } from './server-detail.component';
import { ServerService } from './server.service';

import { ServerType } from '../serverType/serverType';
import { ServerTypeLineComponent } from '../serverType/serverType-line.component';
import { Environment } from '../environment/environment';
import { EnvironmentLineComponent } from '../environment/environment-line.component';

@Component({
    moduleId: module.id,
	templateUrl: 'server-list.component.html',
	selector: 'server-list',
})
export class ServerListComponent {

    @Input() header = "All Servers...";

    // when sub is true, it means this list is a one-to-many list.
    // It belongs to a parent entity, as a result the addNew operation
    // must prefill the parent entity. The prefill is not done here, instead we
    // emit an event.
    @Input() sub : boolean;
    @Output() onAddNewClicked = new EventEmitter();

    serverToDelete : Server;
    displayDeleteDialog : boolean;

    private example : Server = null; // used to query by example...

    // list is paginated
    currentPage : PageResponse<Server> = new PageResponse<Server>(0,0,[]);

    // Many to one: input param is used to filter the list when displayed
    // as a one-to-many list by the other side.
    private _serverType : ServerType;
    private _environment : Environment;

    constructor(private router:Router, private serverService : ServerService, private messageService : MessageService) { }

    loadPage(event : LazyLoadEvent) {
        if (event.filters != undefined && event.filters["name"] != undefined){
            this.example = new Server();
            this.example.name = event.filters["name"].value;
            event.filters["name"].matchMode="contains";
            
        }
        this.serverService.getPage(this.example, event).
            subscribe(
                pageResponse => this.currentPage = pageResponse,
                error => this.messageService.error('Could not get the results', error)
            );
    }

    // Many to one: input param is used to filter the list when displayed
    // as a one-to-many list by the other side.
    @Input()
    set serverType(serverType : ServerType) {
        if (serverType == null) {
            return;
        }
        this._serverType = serverType;

        this.example = new Server();
        this.example.serverType = new ServerType();
        this.example.serverType.id = this._serverType.id;
    }
/*
    @Input()
    set environment(environment : Environment) {
        if (environment == null) {
            return;
        }
        this._environment = environment;

        this.example = new Server();
        this.example.environment = new Environment();
        this.example.environment.id = this._environment.id;
    }
*/

    onRowSelect(event : any) {
        this.router.navigate(['/server', event.data.id]);
    }

    addNew() {
        if (this.sub) {
            this.onAddNewClicked.emit("addNew");
        } else {
            this.router.navigate(['/server', 'new']);
        }
    }

    showDeleteDialog(rowData : any) {
        this.serverToDelete = <Server> rowData;
        this.displayDeleteDialog = true;
    }

    // delete + remove from current page
    delete() {
        this.serverService.delete(this.serverToDelete.id).
            subscribe(
                response => {
                    this.currentPage.remove(this.serverToDelete);
                    this.displayDeleteDialog = false;
                    this.serverToDelete = null;
                    this.messageService.info('Deleted OK', 'PrimeNG Rocks ;-)');
                },
                error => this.messageService.error('Could not delete!', error)
            );
    }
}