//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:src/main/webapp/app/entities/entity.ts.e.vm
//
import {ServerType} from '../serverType/serverType';
import {Node} from '../node/node';
export class Server {
    // Raw attributes
    id : number;
    name : string;
    // x-to-one
    serverType : ServerType;
    node : Node;
}
