//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:src/main/webapp/app/entities/entity.ts.e.vm
//

export class Globalconfig {
    // Raw attributes
    id : number;
    parameter : string;
    value : string;
    hieraAddress : string;
    recursiveByEnv : boolean;
    recursiveByRel : boolean;
    recursiveBySubEnv : boolean;
    notes: string;
    sensitive : boolean;

    constructor(){
        this.parameter = "";
        this.value = "";
        this.hieraAddress = "";
        this.recursiveByEnv = false;
        this.recursiveBySubEnv = false;
        this.recursiveByRel = false;
        this.notes = "";
        this.sensitive = false;
    }

}
