//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:src/main/webapp/app/entities/entity-list.component.ts.e.vm
//
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { Router } from '@angular/router';
import { LazyLoadEvent } from 'primeng/primeng';
import { PageResponse } from "../../support/paging";
import { MessageService } from '../../service/message.service';
import { Globalconfig } from './globalconfig';
import { GlobalconfigDetailComponent } from './globalconfig-detail.component';
import { GlobalconfigService } from './globalconfig.service';
import { Configuration } from '../../support/configuration';

@Component({
    moduleId: module.id,
	templateUrl: 'globalconfig-list.component.html',
	selector: 'globalconfig-list',
})
export class GlobalconfigListComponent {

    @Input() header = "All Globalconfigs...";

    // when sub is true, it means this list is a one-to-many list.
    // It belongs to a parent entity, as a result the addNew operation
    // must prefill the parent entity. The prefill is not done here, instead we
    // emit an event.
    @Input() sub : boolean;
    @Output() onAddNewClicked = new EventEmitter();

    globalconfigToDelete : Globalconfig;
    displayDeleteDialog : boolean;

    private example : Globalconfig = null; // used to query by example...

    // list is paginated
    currentPage : PageResponse<Globalconfig> = new PageResponse<Globalconfig>(0,0,[]);


    constructor(private router:Router, private globalconfigService : GlobalconfigService,
                private messageService : MessageService, private settings : Configuration) { }

    loadPage(event : LazyLoadEvent) {
        this.example = null;
        if (event.filters != undefined){
            if (event.filters["parameter"] != undefined) {
                this.example = new Globalconfig(event.filters["parameter"].value);
                event.filters["parameter"].matchMode="contains";
            }

            if (event.filters["value"] != undefined) {
                if (this.example == undefined)
                    this.example = new Globalconfig().searchByExampleWithValueFactory(event.filters["value"].value);
                else
                    this.example.parameter = event.filters["value"].value;
                event.filters["value"].matchMode="contains";
            }

            if (event.filters["hieraAddress"] != undefined) {            
                if (this.example == undefined)
                    this.example = new Globalconfig().searchByExampleWithAddressFactory(event.filters["hieraAddress"].value);
                else
                    this.example.hieraAddress = event.filters["hieraAddress"].value;
                event.filters["hieraAddress"].matchMode="contains";
                
            }
        }
        
        this.globalconfigService.getPage(this.example, event).
            subscribe(
                pageResponse => this.currentPage = pageResponse,
                error => this.messageService.error('Could not get the results', error)
            );
    }

    onRowSelect(event : any) {
        this.router.navigate(['/globalconfig', event.data.id]);
    }

    addNew() {
        if (this.sub) {
            this.onAddNewClicked.emit("addNew");
        } else {
            this.router.navigate(['/globalconfig', 'new']);
        }
    }

    showDeleteDialog(rowData : any) {
        this.globalconfigToDelete = <Globalconfig> rowData;
        this.displayDeleteDialog = true;
    }

    // delete + remove from current page
    delete() {
        this.globalconfigService.delete(this.globalconfigToDelete.id).
            subscribe(
                response => {
                    this.currentPage.remove(this.globalconfigToDelete);
                    this.displayDeleteDialog = false;
                    this.globalconfigToDelete = null;
                    this.messageService.info('Deleted OK', 'PrimeNG Rocks ;-)');
                },
                error => this.messageService.error('Could not delete!', error)
            );
    }
    
    onDownload(){
        window.location.href=this.settings.createBackendURLFor('api/globalconfigs/configdownload');
    }    
}