//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:src/main/webapp/app/entities/entity-list.component.ts.e.vm
//
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { Router } from '@angular/router';
import { LazyLoadEvent } from 'primeng/primeng';
import { PageResponse } from "../../support/paging";
import { MessageService } from '../../service/message.service';
import { ServerConfig } from './serverConfig';
import { ServerConfigDetailComponent } from './serverConfig-detail.component';
import { ServerConfigService } from './serverConfig.service';

import { Server } from '../server/server';
import { ServerLineComponent } from '../server/server-line.component';

@Component({
    moduleId: module.id,
	templateUrl: 'serverConfig-list.component.html',
	selector: 'serverConfig-list',
})
export class ServerConfigListComponent {

    @Input() header = "All ServerConfigs...";

    // when sub is true, it means this list is a one-to-many list.
    // It belongs to a parent entity, as a result the addNew operation
    // must prefill the parent entity. The prefill is not done here, instead we
    // emit an event.
    @Input() sub : boolean;
    @Output() onAddNewClicked = new EventEmitter();

    serverConfigToDelete : ServerConfig;
    displayDeleteDialog : boolean;

    private example : ServerConfig = null; // used to query by example...

    // list is paginated
    currentPage : PageResponse<ServerConfig> = new PageResponse<ServerConfig>(0,0,[]);

    // Many to one: input param is used to filter the list when displayed
    // as a one-to-many list by the other side.
    private _server : Server;

    constructor(private router:Router, private serverConfigService : ServerConfigService, private messageService : MessageService) { }

    loadPage(event : LazyLoadEvent) {
        this.serverConfigService.getPage(this.example, event).
            subscribe(
                pageResponse => this.currentPage = pageResponse,
                error => this.messageService.error('Could not get the results', error)
            );
    }

    // Many to one: input param is used to filter the list when displayed
    // as a one-to-many list by the other side.
    @Input()
    set server(server : Server) {
        if (server == null) {
            return;
        }
        this._server = server;

        this.example = new ServerConfig();
        this.example.server = new Server();
        this.example.server.id = this._server.id;
    }


    onRowSelect(event : any) {
        this.router.navigate(['/serverConfig', event.data.id]);
    }

    addNew() {
        if (this.sub) {
            this.onAddNewClicked.emit("addNew");
        } else {
            this.router.navigate(['/serverConfig', 'new']);
        }
    }

    showDeleteDialog(rowData : any) {
        this.serverConfigToDelete = <ServerConfig> rowData;
        this.displayDeleteDialog = true;
    }

    // delete + remove from current page
    delete() {
        this.serverConfigService.delete(this.serverConfigToDelete.id).
            subscribe(
                response => {
                    this.currentPage.remove(this.serverConfigToDelete);
                    this.displayDeleteDialog = false;
                    this.serverConfigToDelete = null;
                    this.messageService.info('Deleted OK', 'PrimeNG Rocks ;-)');
                },
                error => this.messageService.error('Could not delete!', error)
            );
    }
}