//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:src/main/webapp/app/entities/entity-detail.component.ts.e.vm
//
import {Component, OnInit, OnDestroy, Input, Output, EventEmitter} from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { SelectItem } from 'primeng/primeng';
import { MessageService} from '../../service/message.service';
import {ServerConfig} from './serverConfig';
import {ServerConfigService} from './serverConfig.service';
import {Server} from '../server/server';

@Component({
    moduleId: module.id,
	templateUrl: 'serverConfig-detail.component.html',
	selector: 'serverConfig-detail',
})
export class ServerConfigDetailComponent implements OnInit, OnDestroy {
    serverConfig : ServerConfig;

    private params_subscription: any;


    @Input() sub : boolean = false;
    @Input() // used to pass the parent when creating a new ServerConfig
    set server(server : Server) {
        this.serverConfig = new ServerConfig();
        this.serverConfig.server = server;
    }

    @Output() onSaveClicked = new EventEmitter<ServerConfig>();
    @Output() onCancelClicked = new EventEmitter();

    constructor(private route: ActivatedRoute, private router: Router, private messageService: MessageService, private serverConfigService: ServerConfigService) {
    }

    ngOnInit() {
        if (this.sub) {
            return;
        }

        this.params_subscription = this.route.params.subscribe(params => {
            let id = params['id'];
            console.log('ngOnInit for serverConfig-detail ' + id);

            if (id === 'new') {
                this.serverConfig = new ServerConfig();
            } else {
                this.serverConfigService.getServerConfig(id)
                    .subscribe(
                        serverConfig => this.serverConfig = serverConfig,
                        error =>  this.messageService.error('ngOnInit error', error)
                    );
            }
        });
    }

    ngOnDestroy() {
        if (!this.sub) {
            this.params_subscription.unsubscribe();
        }
    }

    gotoServer() {
        this.router.navigate(['/server', this.serverConfig.server.id]);
    }

    clearServer() {
        this.serverConfig.server = null;
    }

    onSave() {
        this.serverConfigService.update(this.serverConfig).
            subscribe(
                serverConfig => {
                    this.serverConfig = serverConfig;
                    if (this.sub) {
                        this.onSaveClicked.emit(this.serverConfig);
                        this.messageService.info('Saved OK and msg emitted', 'PrimeNG Rocks ;-)')
                    } else {
                        this.messageService.info('Saved OK', 'PrimeNG Rocks ;-)')
                    }
                },
                error =>  this.messageService.error('Could not save', error)
            );
    }

    onCancel() {
        if (this.sub) {
            this.onCancelClicked.emit("cancel");
            this.messageService.info('Cancel clicked and msg emitted', 'PrimeNG Rocks ;-)')
        }
    }

}
