//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:src/main/webapp/app/entities/entity.ts.e.vm
//
import {Server} from '../server/server';

export class ServerConfig {
    // Raw attributes
    id : number;
    parameter : string;
    value : string;
    hieraAddress : string;
    notes: string;
    sensitive : boolean;
    
    // x-to-one
    server : Server;

    constructor(){
        this.parameter = "";
        this.value = "";
        this.hieraAddress = "";
        this.notes = "";
        this.sensitive = false;
    }
    
}
