//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:src/main/webapp/app/entities/entity-detail.component.ts.e.vm
//
import {Component, OnInit, OnDestroy, Input, Output, EventEmitter} from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { SelectItem } from 'primeng/primeng';
import { MessageService} from '../../service/message.service';
import {PackageInfo} from './packageInfo';
import {PackageInfoService} from './packageInfo.service';
import {PackageType} from '../packageType/packageType';
import {ServerType} from '../serverType/serverType';
import {Release} from '../release/release';

@Component({
    moduleId: module.id,
	templateUrl: 'packageInfo-detail.component.html',
	selector: 'packageInfo-detail',
})
export class PackageInfoDetailComponent implements OnInit, OnDestroy {
    packageInfo : PackageInfo;

    private params_subscription: any;


    @Input() sub : boolean = false;
    @Input() // used to pass the parent when creating a new PackageInfo
    set packageType(packageType : PackageType) {
        this.packageInfo = new PackageInfo();
        this.packageInfo.packageType = packageType;
    }

    @Input() // used to pass the parent when creating a new PackageInfo
    set serverType(serverType : ServerType) {
        this.packageInfo = new PackageInfo();
        this.packageInfo.serverType = serverType;
    }

    @Input() // used to pass the parent when creating a new PackageInfo
    set release(release : Release) {
        this.packageInfo = new PackageInfo();
        this.packageInfo.release = release;
    }

    @Output() onSaveClicked = new EventEmitter<PackageInfo>();
    @Output() onCancelClicked = new EventEmitter();

    constructor(private route: ActivatedRoute, private router: Router, private messageService: MessageService, private packageInfoService: PackageInfoService) {
    }

    ngOnInit() {
        if (this.sub) {
            return;
        }

        this.params_subscription = this.route.params.subscribe(params => {
            let id = params['id'];
            console.log('ngOnInit for packageInfo-detail ' + id);

            if (id === 'new') {
                this.packageInfo = new PackageInfo();
            } else {
                this.packageInfoService.getPackageInfo(id)
                    .subscribe(
                        packageInfo => this.packageInfo = packageInfo,
                        error =>  this.messageService.error('ngOnInit error', error)
                    );
            }
        });
    }

    ngOnDestroy() {
        if (!this.sub) {
            this.params_subscription.unsubscribe();
        }
    }

    gotoPackageType() {
        this.router.navigate(['/packageType', this.packageInfo.packageType.id]);
    }

    clearPackageType() {
        this.packageInfo.packageType = null;
    }

    gotoServerType() {
        this.router.navigate(['/serverType', this.packageInfo.serverType.id]);
    }

    clearServerType() {
        this.packageInfo.serverType = null;
    }

    gotoRelease() {
        this.router.navigate(['/release', this.packageInfo.release.id]);
    }

    clearRelease() {
        this.packageInfo.release = null;
    }

    onSave() {
        this.packageInfoService.update(this.packageInfo).
            subscribe(
                packageInfo => {
                    this.packageInfo = packageInfo;
                    if (this.sub) {
                        this.onSaveClicked.emit(this.packageInfo);
                        this.messageService.info('Saved OK and msg emitted', 'PrimeNG Rocks ;-)')
                    } else {
                        this.messageService.info('Saved OK', 'PrimeNG Rocks ;-)')
                    }
                },
                error =>  this.messageService.error('Could not save', error)
            );
    }

    onCancel() {
        if (this.sub) {
            this.onCancelClicked.emit("cancel");
            this.messageService.info('Cancel clicked and msg emitted', 'PrimeNG Rocks ;-)')
        }
    }

}
