//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:src/main/webapp/app/entities/entity.ts.e.vm
//
import {PackageType} from '../packageType/packageType';
import {ServerType} from '../serverType/serverType';
import {Release} from '../release/release';

export class PackageInfo {
    // Raw attributes
    id : number;
    name : string;
    // x-to-one
    packageType : PackageType;
    serverType : ServerType;
    release : Release;
}
