//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:src/main/webapp/app/entities/entity-list.component.ts.e.vm
//
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { Router } from '@angular/router';
import { LazyLoadEvent } from 'primeng/primeng';
import { PageResponse } from "../../support/paging";
import { MessageService } from '../../service/message.service';
import { EnvironmentConfig } from './environmentConfig';
import { EnvironmentConfigDetailComponent } from './environmentConfig-detail.component';
import { EnvironmentConfigService } from './environmentConfig.service';

import { Environment } from '../environment/environment';
import { EnvironmentLineComponent } from '../environment/environment-line.component';

@Component({
    moduleId: module.id,
	templateUrl: 'environmentConfig-list.component.html',
	selector: 'environmentConfig-list',
})
export class EnvironmentConfigListComponent {

    @Input() header = "All EnvironmentConfigs...";

    // when sub is true, it means this list is a one-to-many list.
    // It belongs to a parent entity, as a result the addNew operation
    // must prefill the parent entity. The prefill is not done here, instead we
    // emit an event.
    @Input() sub : boolean;
    @Output() onAddNewClicked = new EventEmitter();

    environmentConfigToDelete : EnvironmentConfig;
    displayDeleteDialog : boolean;

    private example : EnvironmentConfig = null; // used to query by example...

    // list is paginated
    currentPage : PageResponse<EnvironmentConfig> = new PageResponse<EnvironmentConfig>(0,0,[]);

    // Many to one: input param is used to filter the list when displayed
    // as a one-to-many list by the other side.
    private _environment : Environment;

    constructor(private router:Router, private environmentConfigService : EnvironmentConfigService, private messageService : MessageService) { }

    loadPage(event : LazyLoadEvent) {
        this.environmentConfigService.getPage(this.example, event).
            subscribe(
                pageResponse => this.currentPage = pageResponse,
                error => this.messageService.error('Could not get the results', error)
            );
    }

    // Many to one: input param is used to filter the list when displayed
    // as a one-to-many list by the other side.
    @Input()
    set environment(environment : Environment) {
        if (environment == null) {
            return;
        }
        this._environment = environment;

        this.example = new EnvironmentConfig();
        this.example.environment = new Environment();
        this.example.environment.id = this._environment.id;
    }


    onRowSelect(event : any) {
        this.router.navigate(['/environmentConfig', event.data.id]);
    }

    addNew() {
        if (this.sub) {
            this.onAddNewClicked.emit("addNew");
        } else {
            this.router.navigate(['/environmentConfig', 'new']);
        }
    }

    showDeleteDialog(rowData : any) {
        this.environmentConfigToDelete = <EnvironmentConfig> rowData;
        this.displayDeleteDialog = true;
    }

    // delete + remove from current page
    delete() {
        this.environmentConfigService.delete(this.environmentConfigToDelete.id).
            subscribe(
                response => {
                    this.currentPage.remove(this.environmentConfigToDelete);
                    this.displayDeleteDialog = false;
                    this.environmentConfigToDelete = null;
                    this.messageService.info('Deleted OK', 'PrimeNG Rocks ;-)');
                },
                error => this.messageService.error('Could not delete!', error)
            );
    }
}