//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:src/main/webapp/app/entities/entity-line.component.ts.e.vm
//
import {Component, Input} from '@angular/core';
import {EnvironmentConfig} from './environmentConfig';

@Component({
	template: `
        {{ environmentConfig.parameter }} {{ environmentConfig.value }} {{ environmentConfig.hieraAddress }} 	`,
	selector: 'environmentConfig-line',
})
export class EnvironmentConfigLineComponent {
    @Input() environmentConfig : EnvironmentConfig;
}
