//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:src/main/webapp/app/entities/entity-list.component.ts.e.vm
//
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { Router } from '@angular/router';
import { LazyLoadEvent } from 'primeng/primeng';
import { PageResponse } from "../../support/paging";
import { MessageService } from '../../service/message.service';
import { SubEnvironmentConfig } from './subEnvironmentConfig';
import { SubEnvironmentConfigDetailComponent } from './subEnvironmentConfig-detail.component';
import { SubEnvironmentConfigService } from './subEnvironmentConfig.service';

import { SubEnvironment } from '../environment/subEnvironment';
import { EnvironmentLineComponent } from '../environment/environment-line.component';

@Component({
    moduleId: module.id,
	templateUrl: 'subEnvironmentConfig-list.component.html',
	selector: 'subEnvironmentConfig-list',
})
export class SubEnvironmentConfigListComponent {

    @Input() header = "All EnvironmentConfigs...";

    // when sub is true, it means this list is a one-to-many list.
    // It belongs to a parent entity, as a result the addNew operation
    // must prefill the parent entity. The prefill is not done here, instead we
    // emit an event.
    @Input() sub : boolean;
    @Output() onAddNewClicked = new EventEmitter();

    subEnvironmentConfigToDelete : SubEnvironmentConfig;
    displayDeleteDialog : boolean;

    private example : SubEnvironmentConfig = null; // used to query by example...

    // list is paginated
    currentPage : PageResponse<SubEnvironmentConfig> = new PageResponse<SubEnvironmentConfig>(0,0,[]);

    // Many to one: input param is used to filter the list when displayed
    // as a one-to-many list by the other side.
    private _subEnvironment : SubEnvironment;

    constructor(private router:Router, private subEnvironmentConfigService : SubEnvironmentConfigService, private messageService : MessageService) { }

    loadPage(event : LazyLoadEvent) {
        this.subEnvironmentConfigService.getPage(this.example, event).
            subscribe(
                pageResponse => this.currentPage = pageResponse,
                error => this.messageService.error('Could not get the results', error)
            );
    }

    // Many to one: input param is used to filter the list when displayed
    // as a one-to-many list by the other side.
    @Input()
    set subEnvironment(subEnvironment : SubEnvironment) {
        if (subEnvironment == null) {
            return;
        }
        this._subEnvironment = subEnvironment;

        this.example = new SubEnvironmentConfig();
        this.example.subEnvironment = new SubEnvironment();
        this.example.subEnvironment.id = this._subEnvironment.id;
    }


    onRowSelect(event : any) {
        this.router.navigate(['/subEnvironmentConfig', event.data.id]);
    }

    addNew() {
        if (this.sub) {
            this.onAddNewClicked.emit("addNew");
        } else {
            this.router.navigate(['/subEnvironmentConfig', 'new']);
        }
    }

    showDeleteDialog(rowData : any) {
        this.subEnvironmentConfigToDelete = <SubEnvironmentConfig> rowData;
        this.displayDeleteDialog = true;
    }

    // delete + remove from current page
    delete() {
        this.subEnvironmentConfigService.delete(this.subEnvironmentConfigToDelete.id).
            subscribe(
                response => {
                    this.currentPage.remove(this.subEnvironmentConfigToDelete);
                    this.displayDeleteDialog = false;
                    this.subEnvironmentConfigToDelete = null;
                    this.messageService.info('Deleted OK', 'PrimeNG Rocks ;-)');
                },
                error => this.messageService.error('Could not delete!', error)
            );
    }
}